spring.application.name=bookstore
spring.profiles.active=local-postgre
spring.jpa.show-sql=true

#local database
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.url=jdbc:postgresql://localhost:5432/k26Bookstore
spring.datasource.username=postgres
spring.datasource.password=HAVoc15l4abNo8OP

#JPA/hibernate ei tee muutoksia ulkoiseen kantaan
spring.jpa.hibernate.ddl-auto=none